server:
    port: 8080
    context-path: /sell


spring:
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        username: root
        password: root
        url: jdbc:mysql://localhost/order_food?characterEncoding=utf-8&useSSL=false
    jpa:
        show-sql: true
    jackson:
        default-property-inclusion: non_null #值为Null时，不返回
    redis:
        host: 127.0.0.1
        port: 6379
        pool:
            # 连接池中的最大空闲连接
            max-idle: 20
            # 连接池中的最小空闲连接
            min-idle: 1
            # 连接池最大连接数（使用负值表示没有限制）
            max-active: 20
            max-wait: 60000
        #默认是索引为0的数据库
        database: 0
        # 连接超时时间（毫秒）
        timeout: 600000


